### PR TITLE
fix: version 1.0.3 ready for review

### PR DESCRIPTION
**Pull request by iccowan**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes freeCodeCamp/freeCodeCamp#43936
Closes freeCodeCamp/freeCodeCamp#43856

Fixes (in changelog):
- Fix incorrect list of unique winning teams in `expected_output.txt`
- Fix typos in `expected_output.txt` and `queries.sh`
- Clarify wording for number of goals scored in `expected_output.txt` and `queries.sh`

I skipped v1.0.2 because that branch already exists and I saw from a previous PR that there were issues with it working, so I went with v1.0.3. If I need to change the version, I can do that and create a new PR.

### CODE REVIEW

**Comment by gikf** [comment]
Yes! That's how it should be :rocket:.

Now, because commit hashes changed it's needed to generate new `tutorial.json` file using the CodeRoad cli, on branch based off the `main` branch.

Before that, I've found couple things for changing on the version branch:
- There's another copy of expected_output.txt file, - `.freeCodeCamp/expected_output.txt` which is used in test, changes needs to be done in it as well
- Small typo in Eight**h**-Final - missing letter
- Seems like during the correcting list of teams, the lists got mixed up - changes were made under the list with all winning teams.

And before that, if you are up for it, I've noticed issue in the data set for the project. In the .csv the matches in the Eighth-Final, for year 2014 are repeated from 2018 year, but they were actually different - https://www.fifa.com/tournaments/mens/worldcup/2014brazil/match-center. Changing data set would mean the need to add even more corrections to the expected output, so I'd understand if you wouldn't want to do that yet.

**Comment by iccowan** [comment]
> Yes! That's how it should be 🚀.
> 
> Now, because commit hashes changed it's needed to generate new `tutorial.json` file using the CodeRoad cli, on branch based off the `main` branch (on your `fix/version-1.0.3` branch).
> 
> Before that, I've found couple things for changing on the version branch:
> 
> * There's another copy of expected_output.txt file, - `.freeCodeCamp/expected_output.txt` which is used in test, changes needs to be done in it as well
> * Small typo in Eight**h**-Final - missing letter
> * ~Seems like during the correcting list of teams, the lists got mixed up - changes were made under the list with all winning teams.~ I was wrong here.
> 
> It'd be great if along those above you could change one more thing, the line below needs to have `.freecodecamp` capitalized: `.freeCodeCamp`
> 
> https://github.com/freeCodeCamp/learn-world-cup-database/blob/76d45ba9f98ce4fa02459c14751898605abaadff/.freeCodeCamp/test/1.1.test.js#L183
> 
> And before that, if you are up for it, I've noticed issue in the data set for the project. In the .csv the matches in the Eighth-Final, for year 2014 are repeated from 2018 year, but they were actually different - https://www.fifa.com/tournaments/mens/worldcup/2014brazil/match-center. Changing data set would mean the need to add even more corrections to the expected output, so I'd understand if you wouldn't want to do that yet.

**Comment by iccowan** [comment]
@gikf All changes are made!

**Comment by iccowan** [comment]
> Thanks @iccowan for update, we are getting closer. Couple of issues below.

Just pushed an update with fixes to those. Thank you for helping me out with this... I'm fairly new with CodeRoad tutorials!

**Comment by iccowan** [comment]
> iccowan all looks good to me, thanks for the fixes 🚀.

Thanks for the help!

**Comment by moT01** [comment]
Thanks for the work on this @iccowan and @gikf 🎉 It looks real good.

I created a `v1.0.2` branch off of your `v1.0.3` (since we never ended up adding it) and added a few things that were brought up by others. The only thing I changed that you had was USA -> United States (I just liked it better). The other additions are in the changelog. If either of you feel like giving it a test, let me know how it goes 👍

I created a different PR to use that v1.0.2 branch - these commits are on it. I'm still figuring out how to best go about adding changes like this. I went that route this time, so we can close this.

Thanks again for the work, and happy coding 🚀

**Comment by iccowan** [comment]
> Thanks for the work on this @iccowan and @gikf 🎉 It looks real good.
> 
> I created a `v1.0.2` branch off of your `v1.0.3` (since we never ended up adding it) and added a few things that were brought up by others. The only thing I changed that you had was USA -> United States (I just liked it better). The other additions are in the changelog. If either of you feel like giving it a test, let me know how it goes 👍
> 
> I created a different PR to use that v1.0.2 branch - these commits are on it. I'm still figuring out how to best go about adding changes like this. I went that route this time, so we can close this.
> 
> Thanks again for the work, and happy coding 🚀

Looks great. Thank you!

**Pull request closed without merging**
